<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRqMeQUu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRqMeQUu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRqMeQUu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRqMeQUu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRqMeQUu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RqMeQUu',
    'container.build_id' => 'ff4b5e46',
    'container.build_time' => 1678629683,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRqMeQUu');
