<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Proveedor__CLASSMETADATA__' => 0,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Proveedor',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Proveedor',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ProveedorRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'Nombre' => [
                            'fieldName' => 'Nombre',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 30,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nombre',
                        ],
                        'Correo' => [
                            'fieldName' => 'Correo',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 50,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'correo',
                        ],
                        'Telefono' => [
                            'fieldName' => 'Telefono',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 20,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'telefono',
                        ],
                        'Tipo' => [
                            'fieldName' => 'Tipo',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 20,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'tipo',
                        ],
                        'Estado' => [
                            'fieldName' => 'Estado',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 20,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'estado',
                        ],
                        'Creado' => [
                            'fieldName' => 'Creado',
                            'type' => 'datetime',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'creado',
                        ],
                        'Editado' => [
                            'fieldName' => 'Editado',
                            'type' => 'datetime',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'editado',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nombre' => 'Nombre',
                        'correo' => 'Correo',
                        'telefono' => 'Telefono',
                        'tipo' => 'Tipo',
                        'estado' => 'Estado',
                        'creado' => 'Creado',
                        'editado' => 'Editado',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nombre' => 'nombre',
                        'Correo' => 'correo',
                        'Telefono' => 'telefono',
                        'Tipo' => 'tipo',
                        'Estado' => 'estado',
                        'Creado' => 'creado',
                        'Editado' => 'editado',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'proveedor',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
