<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM7cp8W1\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM7cp8W1/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerM7cp8W1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerM7cp8W1\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerM7cp8W1\srcApp_KernelProdContainer([
    'container.build_hash' => 'M7cp8W1',
    'container.build_id' => '8eccbbbd',
    'container.build_time' => 1678628557,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM7cp8W1');
