<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_editar' => [['id'], ['_controller' => 'App\\Controller\\EditarController::index'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/editar']], [], []],
    'app_eliminar' => [['id'], ['_controller' => 'App\\Controller\\EliminarController::index'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/eliminar']], [], []],
    'app_registro' => [[], ['_controller' => 'App\\Controller\\RegistroController::index'], [], [['text', '/registro']], [], []],
    'app_tabla' => [[], ['_controller' => 'App\\Controller\\TablaController::index'], [], [['text', '/']], [], []],
];
